version: "3"

volumes:
  db-volume:

services:
  auto-catalog:
    container_name: auto-catalog
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto
      SPRING_DATASOURCE_USERNAME: Alex
      SPRING_DATASOURCE_PASSWORD: Alex
      KEYCLOAK_AUTH-SERVER-URL: http://keycloak:8484/auth
      KEYCLOAK_REALM: catalog-realm
      KEYCLOAK_RESOURCE: catalog-client
      KEYCLOAK_PUBLIC-CLIENT: true


  auto-shop:
    container_name: auto-shop
    build: /Users/lexkml/IdeaProjects/red-collar/auto-shop
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - auto-catalog
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto
      SPRING_DATASOURCE_USERNAME: Alex
      SPRING_DATASOURCE_PASSWORD: Alex
      AUTOCATALOGAPI_FEIGN_NAME: autoCatalogApi
      AUTOCATALOGAPI_FEIGN_URL: http://localhost:8080

  keycloak:
    image: koolwithk/keycloak-arm:16.0.0
    container_name: keycloak
    environment:
      DB_ADDR: postgres
      DB_DATABASE: auto
      DB_USER: Alex
      DB_PASSWORD: Alex
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8484:8080"
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: library/postgres
    volumes:
      - db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: auto
      POSTGRES_USER: Alex
      POSTGRES_PASSWORD: Alex
    ports:
      - "5434:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitMQ
    ports:
      - "5672:5672"
      - "15672:15672"
