spring:
  datasource:
    username: Alex
    password: Alex
    url: jdbc:postgresql://localhost:5432/auto
    hikari:
      schema: catalog

  flyway:
    schemas: catalog
    baseline-on-migrate: true
